### ISSUE TITLE
Change axios to undici

### ISSUE THREAD

**Issue by sergeyampo** [SocketSomeone/cent.js#402]
What do you think about replace axios with undici because undici is more robust and performant that axios. Also, undici is developed by nodejs team and in the next LTS is going to become stable and used as internal library.

**Comment by SocketSomeone** [comment]
@sergeyampo

Hi there,

Thank you for your suggestion! Of course, we can replace axios with breaking changes at 2.0.0, cuz cent client inherited from axios client. Wanna create PR?

**Comment by SocketSomeone** [comment]
Changed at https://github.com/SocketSomeone/cent.js/releases/tag/3.0.0
