### ISSUE TITLE
About the compatibility of the undici package with VITE

### ISSUE THREAD

**Issue by koch3092** [SocketSomeone/cent.js#483]
After changing to undici, it does not perform well in the Vite project, it will prompt a series of errors such as "global is not defined", is there a good compatible solution?

**Comment by koch3092** [comment]
Maybe I can use v2.1.0?

**Comment by SocketSomeone** [comment]
Hi, there! @koch3092 Thank you for issue!

Can you create min repro for issue?

> Maybe I can use v2.1.0?

Yes, you can!
